<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>detail</title>
</head>
<body>
    <table>
        <tr>
            <th>studentId</th>
            <td>${hakjum.studentId}</td>
        </tr>
        <tr>
            <th>studentName</th>
   			 <td>${hakjum.studentName}</td>
        </tr>
        <tr>
            <th>koreanScore</th>
   			 <td>${hakjum.koreanScore}</td>
        </tr>
        <tr>
            <th>englishScore</th>
            <td>${hakjum.englishScore}</td>
        </tr>
        <tr>
            <th>mathScore</th>
 			 <td>${hakjum.mathScore}</td>
        </tr>
    </table>
</body>
</html>